SELECT
	INVOICE.LOGICALREF,
	INVOICE.CLIENTREF,
	INVOICE.DATE_,
	INVOICE.NETTOTAL,
	INVOICE.CANCELLED,
	INVOICE.READONLY,
	(SELECT T.DEFINITION_ FROM LG_$FIRM$_CLCARD T WHERE T.LOGICALREF = INVOICE.CLIENTREF) CLCARD_____DEFINITION_
FROM
LG_$FIRM$_$PERIOD$_INVOICE INVOICE
$WHERE$
$ORDER$
$LIMIT$
