SELECT
LN.STOCKREF,
SUM(
( 
CASE 
	WHEN LN.IOCODE IN (1,2) THEN +1 
	WHEN LN.IOCODE IN (3,4) THEN -1 
	ELSE 0 
END 
)*LN.AMOUNT) AMOUNT
FROM
LG_$FIRM$_$PERIOD$_STLINE LN
WHERE
LN.CANCELLED = 0
GROUP BY LN.STOCKREF