//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaAgent.AvaExt.SQL.Dynamic.Resource
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class SqlPattern {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal SqlPattern() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaAgent.AvaExt.SQL.Dynamic.Resource.SqlPattern", typeof(SqlPattern).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///{1}.*
        ///FROM
        ///$CATALOG$..{0} {1}
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilder {
            get {
                return ResourceManager.GetString("PatternSqlBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///KSLINES.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_KSLINES KSLINES
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderCashTrans {
            get {
                return ResourceManager.GetString("PatternSqlBuilderCashTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CLCARD.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_CLCARD CLCARD
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderClient {
            get {
                return ResourceManager.GetString("PatternSqlBuilderClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///GNTOTCL.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_GNTOTCL GNTOTCL
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderClientGenStat {
            get {
                return ResourceManager.GetString("PatternSqlBuilderClientGenStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///PAYTRANS.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_PAYTRANS PAYTRANS
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderClientPayTrans {
            get {
                return ResourceManager.GetString("PatternSqlBuilderClientPayTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CLFLINE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_CLFLINE CLFLINE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderClientTrans {
            get {
                return ResourceManager.GetString("PatternSqlBuilderClientTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CLFLINE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_CLFLINE CLFLINE
        ///INNER JOIN
        ///$CATALOG$..LG_$FIRM$_CLCARD CLCARD
        ///ON CLFLINE.CLIENTREF = CLCARD.LOGICALREF
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderClientTransClientFiltered {
            get {
                return ResourceManager.GetString("PatternSqlBuilderClientTransClientFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CAMPAIGN.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_CAMPAIGN CAMPAIGN
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderCompCard {
            get {
                return ResourceManager.GetString("PatternSqlBuilderCompCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CMPGNLINE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_CMPGNLINE CMPGNLINE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderCompCardLine {
            get {
                return ResourceManager.GetString("PatternSqlBuilderCompCardLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CURRENCYLIST.*
        ///FROM
        ///$CATALOG$..L_CURRENCYLIST CURRENCYLIST
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderCurrencyList {
            get {
                return ResourceManager.GetString("PatternSqlBuilderCurrencyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///DAILYEXCHANGES.*
        ///FROM
        ///$CATALOG$..L_DAILYEXCHANGES DAILYEXCHANGES
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderDailyExchanges {
            get {
                return ResourceManager.GetString("PatternSqlBuilderDailyExchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///T_DEP.*
        ///FROM
        ///$CATALOG$..L_CAPIDEPT T_DEP
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderDep {
            get {
                return ResourceManager.GetString("PatternSqlBuilderDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///T_DIV.*
        ///FROM
        ///$CATALOG$..L_CAPIDIV T_DIV
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderDiv {
            get {
                return ResourceManager.GetString("PatternSqlBuilderDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///FIRMDOC.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_FIRMDOC FIRMDOC
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderDocFirm {
            get {
                return ResourceManager.GetString("PatternSqlBuilderDocFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///DOCNUM.*
        ///FROM
        ///$CATALOG$..L_LDOCNUM DOCNUM
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderDocNum {
            get {
                return ResourceManager.GetString("PatternSqlBuilderDocNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///PERDOC.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_PERDOC PERDOC
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderDocPer {
            get {
                return ResourceManager.GetString("PatternSqlBuilderDocPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///SUM(GNTOTCL.DEBIT) DEBIT,SUM(GNTOTCL.CREDIT) CREDIT
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_GNTOTCL GNTOTCL INNER JOIN $CATALOG$..LG_$FIRM$_CLCARD CLCARD ON GNTOTCL.CARDREF = CLCARD.LOGICALREF
        ///$WHERE$
        ///$ORDER$
        ///.
        /// </summary>
        internal static string PatternSqlBuilderDynClientGroupGenStat {
            get {
                return ResourceManager.GetString("PatternSqlBuilderDynClientGroupGenStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///T_FACK.*
        ///FROM
        ///$CATALOG$..L_CAPIFACTORY T_FACK
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderFack {
            get {
                return ResourceManager.GetString("PatternSqlBuilderFack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///T_FIRM.*
        ///FROM
        ///$CATALOG$..L_CAPIFIRM T_FIRM
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderFirm {
            get {
                return ResourceManager.GetString("PatternSqlBuilderFirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///FIRMPARAMS.*
        ///FROM
        ///$CATALOG$..L_FIRMPARAMS FIRMPARAMS
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderFirmParams {
            get {
                return ResourceManager.GetString("PatternSqlBuilderFirmParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///INVOICE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_INVOICE INVOICE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderInvoice {
            get {
                return ResourceManager.GetString("PatternSqlBuilderInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///INVOICE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_INVOICE INVOICE
        ///INNER JOIN
        ///$CATALOG$..LG_$FIRM$_CLCARD CLCARD
        ///ON INVOICE.CLIENTREF = CLCARD.LOGICALREF
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderInvoiceClientFiltered {
            get {
                return ResourceManager.GetString("PatternSqlBuilderInvoiceClientFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///SPECODES.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_SPECODES SPECODES
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderMarkingCodes {
            get {
                return ResourceManager.GetString("PatternSqlBuilderMarkingCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///ITEMS.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_ITEMS ITEMS
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderMaterial {
            get {
                return ResourceManager.GetString("PatternSqlBuilderMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///GNTOTST.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_GNTOTST GNTOTST
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderMaterialGenStat {
            get {
                return ResourceManager.GetString("PatternSqlBuilderMaterialGenStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///STLINE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_STLINE STLINE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderMaterialTrans {
            get {
                return ResourceManager.GetString("PatternSqlBuilderMaterialTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///ITMUNITA.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_ITMUNITA ITMUNITA
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderMaterialUnits {
            get {
                return ResourceManager.GetString("PatternSqlBuilderMaterialUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///UNITBARCODE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_UNITBARCODE UNITBARCODE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderMaterialUnitsBarcode {
            get {
                return ResourceManager.GetString("PatternSqlBuilderMaterialUnitsBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///LN.STOCKREF,
        ///SUM(
        ///( 
        ///CASE 
        ///	WHEN LN.IOCODE IN (1,2) THEN +1 
        ///	WHEN LN.IOCODE IN (3,4) THEN -1 
        ///	ELSE 0 
        ///END 
        ///)*LN.AMOUNT) AMOUNT
        ///FROM
        ///LG_$FIRM$_$PERIOD$_STLINE LN
        ///WHERE
        ///LN.CANCELLED = 0
        ///GROUP BY LN.STOCKREF.
        /// </summary>
        internal static string PatternSqlBuilderMatsIO {
            get {
                return ResourceManager.GetString("PatternSqlBuilderMatsIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///ORFICHE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_ORFICHE ORFICHE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderOrder {
            get {
                return ResourceManager.GetString("PatternSqlBuilderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///ORFICHE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_ORFICHE ORFICHE
        ///INNER JOIN
        ///$CATALOG$..LG_$FIRM$_CLCARD CLCARD
        ///ON ORFICHE.CLIENTREF = CLCARD.LOGICALREF
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderOrderClientFiltered {
            get {
                return ResourceManager.GetString("PatternSqlBuilderOrderClientFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///ORFLINE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_ORFLINE ORFLINE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderOrderTrans {
            get {
                return ResourceManager.GetString("PatternSqlBuilderOrderTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///T_PERIOD.*
        ///FROM
        ///$CATALOG$..L_CAPIPERIOD T_PERIOD
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderPeriod {
            get {
                return ResourceManager.GetString("PatternSqlBuilderPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///PRCLIST.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_PRCLIST PRCLIST
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderPriceList {
            get {
                return ResourceManager.GetString("PatternSqlBuilderPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///SLSMAN.*
        ///FROM
        ///$CATALOG$..LG_SLSMAN SLSMAN
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderSalesMan {
            get {
                return ResourceManager.GetString("PatternSqlBuilderSalesMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///SLSCLREL.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_SLSCLREL SLSCLREL
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderSalesManClientRel {
            get {
                return ResourceManager.GetString("PatternSqlBuilderSalesManClientRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///INVOICE.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_$PERIOD$_INVOICE INVOICE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderSlip {
            get {
                return ResourceManager.GetString("PatternSqlBuilderSlip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///TRADGRP.*
        ///FROM
        ///$CATALOG$..L_TRADGRP TRADGRP
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderTradingGroup {
            get {
                return ResourceManager.GetString("PatternSqlBuilderTradingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///UNITSETL.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_UNITSETL UNITSETL
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderUnits {
            get {
                return ResourceManager.GetString("PatternSqlBuilderUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///UNITSETF.*
        ///FROM
        ///$CATALOG$..LG_$FIRM$_UNITSETF UNITSETF
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderUnitSet {
            get {
                return ResourceManager.GetString("PatternSqlBuilderUnitSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///T_USER.*
        ///FROM
        ///$CATALOG$..L_CAPIUSER T_USER
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderUser {
            get {
                return ResourceManager.GetString("PatternSqlBuilderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///WHOUSE.*
        ///FROM
        ///$CATALOG$..L_CAPIWHOUSE WHOUSE
        ///$WHERE$
        ///$ORDER$.
        /// </summary>
        internal static string PatternSqlBuilderWarehouse {
            get {
                return ResourceManager.GetString("PatternSqlBuilderWarehouse", resourceCulture);
            }
        }
    }
}
