//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvaAgent.AvaExt.Expression.Resource
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class ScriptText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ScriptText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvaAgent.AvaExt.Expression.Resource.ScriptText", typeof(ScriptText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Deployment ;
        ///using System.Data ;
        ///using System.Xml ;
        ///using System.Drawing ;
        ///
        ///            
        ///namespace EvalNamespace 
        ///{
        ///    public class EvalClass
        ///    {
        ///      $BODY$
        ///    }
        ///}.
        /// </summary>
        internal static string ClassEvalStub {
            get {
                return ResourceManager.GetString("ClassEvalStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Deployment ;
        ///using System.Data ;
        ///using System.Xml ;
        ///using System.Drawing ;
        ///
        ///            
        ///namespace EvalNamespace 
        ///{
        ///    public class EvalClass
        ///    {
        ///         public object main($PARAMETERS$)
        ///         {
        ///         $BODY$
        ///         return null;
        ///         }
        ///         
        ///         object IIF(bool b,object v1,object v2)
        ///         {
        ///			return (b?v1:v2);
        ///         }
        ///    }
        ///}.
        /// </summary>
        internal static string ScriptEvalStub {
            get {
                return ResourceManager.GetString("ScriptEvalStub", resourceCulture);
            }
        }
    }
}
