CREATE TABLE LG_$FIRM$_CLCARD (
	LOGICALREF NVARCHAR(40) NOT NULL COLLATE NOCASE,
	CODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	DEFINITION_ NVARCHAR(50) NULL COLLATE NOCASE DEFAULT '',
	SPECODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	CYPHCODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	CLGRPCODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	CLGRPCODESUB NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	PRCLIST SMALLINT NULL DEFAULT 0,
	BALANCE FLOAT NULL DEFAULT 0,
	BALANCEIO FLOAT NULL DEFAULT 0,
	BALANCELIMIT FLOAT NULL DEFAULT 0,
	ORDDAY NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	SPE_ORDDAY NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	DISCPER FLOAT NULL DEFAULT 0,
	BARCODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	FILTERPROMOCL NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	RECVERS SMALLINT NULL DEFAULT 0,
	CREATEDDATE DATETIME NULL DEFAULT '1900-01-01',
	LASTTRANS VARCHAR(500) NULL COLLATE NOCASE DEFAULT '', 
	UNIONCODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	CONSTRAINT I$FIRM$_CLCARD_I1 PRIMARY KEY (LOGICALREF),
	CONSTRAINT I$FIRM$_CLCARD_I2 UNIQUE (CODE)
	)
GO

CREATE INDEX I$FIRM$_CLCARD_I3 ON LG_$FIRM$_CLCARD (BARCODE)
GO
CREATE INDEX I$FIRM$_CLCARD_I4 ON LG_$FIRM$_CLCARD (CLGRPCODE,CLGRPCODESUB)
GO
CREATE TABLE LG_$FIRM$_ITEMS (
	LOGICALREF NVARCHAR(40) NOT NULL COLLATE NOCASE,
	CODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	NAME NVARCHAR(50) NULL COLLATE NOCASE DEFAULT '',
	STGRPCODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	STGRPCODESUB NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	UNIT1 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	UNIT2 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	UNIT3 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	UNITREF1 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	UNITREF2 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	UNITREF3 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	UNITCF1 FLOAT NULL DEFAULT 0,
	UNITCF2 FLOAT NULL DEFAULT 0,
	UNITCF3 FLOAT NULL DEFAULT 0,
	PRICE0 FLOAT NULL DEFAULT 0,
	PRICE1 FLOAT NULL DEFAULT 0,
	PRICE2 FLOAT NULL DEFAULT 0,
	PRICE3 FLOAT NULL DEFAULT 0,
	PRICE4 FLOAT NULL DEFAULT 0,
	PRICE5 FLOAT NULL DEFAULT 0,
	COSTPRC FLOAT NULL DEFAULT 0,
	BARCODE1 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	BARCODE2 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	BARCODE3 NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	VOLUME_ FLOAT NULL DEFAULT 0,
	WEIGHT FLOAT NULL DEFAULT 0,
	ONHAND FLOAT NULL DEFAULT 0,
	ONHANDIO FLOAT NULL DEFAULT 0,
	ONMAIN FLOAT NULL DEFAULT 0,
	SPE_REMAIN FLOAT NULL DEFAULT 0,
	SPE_PRICE FLOAT NULL DEFAULT 0,
	PROMO SMALLINT NULL DEFAULT 0,
	RECVERS SMALLINT NULL DEFAULT 0,
	CREATEDDATE DATETIME NULL DEFAULT '1900-01-01',
	CONSTRAINT I$FIRM$_ITEMS_I1 PRIMARY KEY (LOGICALREF),
	CONSTRAINT I$FIRM$_ITEMS_I2 UNIQUE (CODE)
	)
GO

CREATE INDEX I$FIRM$_ITEMS_I3 ON LG_$FIRM$_ITEMS (BARCODE1)
GO
CREATE INDEX I$FIRM$_ITEMS_I4 ON LG_$FIRM$_ITEMS (BARCODE2)
GO
CREATE INDEX I$FIRM$_ITEMS_I5 ON LG_$FIRM$_ITEMS (BARCODE3)
GO
CREATE INDEX I$FIRM$_ITEMS_I6 ON LG_$FIRM$_ITEMS (STGRPCODE,STGRPCODESUB)
GO

CREATE TABLE LG_$FIRM$_INFOFIRM (
	LOGICALREF NVARCHAR(40) NOT NULL COLLATE NOCASE,
	CODE NVARCHAR(40) NULL COLLATE NOCASE DEFAULT '',
	VALUE_ NVARCHAR(50) NULL COLLATE NOCASE DEFAULT '',
	CONSTRAINT I$FIRM$_INFOFIRM_I1 PRIMARY KEY (LOGICALREF)
	)
GO


