SELECT
CLCARD.LOGICALREF,
CLCARD.CODE,
CLCARD.DEFINITION_,
CLCARD.SPECODE,
CLCARD.CYPHCODE,
CLCARD.CLGRPCODE,
CLCARD.CLGRPCODESUB,
CLCARD.PRCLIST,
CLCARD.BALANCE,
CLCARD.BALANCEIO,
CLCARD.BALANCELIMIT,
CLCARD.ORDDAY,
CLCARD.SPE_ORDDAY,
CLCARD.DISCPER,
CLCARD.BARCODE,
CLCARD.FILTERPROMOCL,
CLCARD.RECVERS,
CLCARD.CREATEDDATE,
CLCARD.UNIONCODE,
(CLCARD.BALANCE+CLCARD.BALANCEIO) CLCARD_____BALANCE 
FROM
LG_$FIRM$_CLCARD CLCARD
$WHERE$
$ORDER$
$LIMIT$
