select
H.*
from
LG_$FIRM$_$PERIOD$_KSLINES H
where
H.LOGICALREF = @lref
GO
select
CL.CODE,
CL.DEFINITION_,
IFNULL(CL.BALANCE,0.0) BALANCE,
IFNULL(SALE.TOTAL,0.0) SALE,
IFNULL(SRETURN.TOTAL,0.0) SRETURN,
IFNULL(CASH.TOTAL,0.0) CASH
from
LG_$FIRM$_CLCARD CL 
left join
(
	select
	sum(DOC.NETTOTAL) TOTAL,
	DOC.CLIENTREF
	from
	LG_$FIRM$_$PERIOD$_INVOICE DOC
	where
	DOC.TRCODE = 8 and
	DOC.CANCELLED = 0 and
	DOC.CLIENTREF = @crefS
	group by DOC.CLIENTREF
) SALE
on CL.LOGICALREF = SALE.CLIENTREF
left join
(
	select
	sum(DOC.NETTOTAL) TOTAL,
	DOC.CLIENTREF
	from
	LG_$FIRM$_$PERIOD$_INVOICE DOC
	where
	DOC.TRCODE = 3 and
	DOC.CANCELLED = 0 and
	DOC.CLIENTREF = @crefR
	group by DOC.CLIENTREF
) SRETURN
on CL.LOGICALREF = SRETURN.CLIENTREF
left join
(
	select
	sum(DOC.AMOUNT) TOTAL,
	DOC.CLIENTREF
	from
	LG_$FIRM$_$PERIOD$_KSLINES DOC
	where
	DOC.TRCODE = 11 and
	DOC.CANCELLED = 0 and
	DOC.CLIENTREF = @crefC
	group by DOC.CLIENTREF
) CASH
on CL.LOGICALREF = CASH.CLIENTREF
where
CL.LOGICALREF = @cref
GO
update LG_$FIRM$_$PERIOD$_INVOICE set READONLY = 1 where CLIENTREF = @cref
GO
update LG_$FIRM$_$PERIOD$_KSLINES set READONLY = 1 where CLIENTREF = @cref
GO

