SELECT
CL.DEFINITION_ NAME, 
(DOC.GROSSTOTAL-DOC.TOTALPROMOTIONS) TOTAL,
DOC.NETTOTAL TOTALNET,
(DOC.TOTALDISCOUNTS-DOC.TOTALPROMOTIONS) DISCOUNT,
SUBSTR( DOC.GENEXP1 , 1, 1 ) GENEXP1
FROM 
LG_$FIRM$_$PERIOD$_INVOICE DOC 
INNER JOIN
LG_$FIRM$_CLCARD CL 
ON DOC.CLIENTREF = CL.LOGICALREF
WHERE 
DOC.TRCODE = 8 AND
DOC.CANCELLED = 0 
ORDER BY DOC.DATE_ DESC
GO
