SELECT
DOC.DATE_,
SUBSTR( CL.DEFINITION_ , 1, 25 ) NAME,
DOC.NETTOTAL TOTAL,
SUBSTR( DOC.GENEXP1 , 1, 1 ) GENEXP1
FROM 
LG_$FIRM$_$PERIOD$_INVOICE DOC 
INNER JOIN
LG_$FIRM$_CLCARD CL 
ON DOC.CLIENTREF = CL.LOGICALREF
WHERE 
DOC.TRCODE = 8 AND
DOC.CANCELLED = 0 
ORDER BY DOC.DATE_ ASC
GO
SELECT
DOC.DATE_,
SUBSTR( CL.DEFINITION_ , 1, 25 ) NAME,
DOC.NETTOTAL TOTAL,
SUBSTR( DOC.GENEXP1 , 1, 1 ) GENEXP1
FROM 
LG_$FIRM$_$PERIOD$_INVOICE DOC 
INNER JOIN
LG_$FIRM$_CLCARD CL 
ON DOC.CLIENTREF = CL.LOGICALREF
WHERE 
DOC.TRCODE = 3 AND
DOC.CANCELLED = 0 
ORDER BY DOC.DATE_ ASC
GO
SELECT
DOC.DATE_,
SUBSTR( CL.DEFINITION_ , 1, 25 ) NAME,
DOC.AMOUNT TOTAL,
SUBSTR( DOC.LINEEXP , 1, 1 ) GENEXP1
FROM 
LG_$FIRM$_$PERIOD$_KSLINES DOC 
INNER JOIN
LG_$FIRM$_CLCARD CL 
ON DOC.CLIENTREF = CL.LOGICALREF
WHERE 
DOC.TRCODE = 11 AND
DOC.CANCELLED = 0 
ORDER BY DOC.DATE_ ASC
GO

