#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AvaAgent.Resource", IsApplication=true)]

namespace AvaAgent
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int colorGridCellBackground = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int colorGridCellText = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int colorGridHeaderBackground = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int colorGridHeaderText = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int colorGridSelectedBackground = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int colorGridSelectedText = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int color_grey_1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int color_grey_2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int color_grey_3 = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060003
			public const int height1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int height2 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int height3 = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int padding1 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int padding2 = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int text1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int text2 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int text3 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int width1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int width2 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int width3 = 2131099656;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_add_group = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_add_person = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_cast = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_cast_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_network_wifi = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_new = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_overflow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_remove = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int main = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080024
			public const int cAmount = 2131230756;
			
			// aapt resource value: 0x7f08001b
			public const int cBarcode = 2131230747;
			
			// aapt resource value: 0x7f080017
			public const int cBtnAdd = 2131230743;
			
			// aapt resource value: 0x7f080041
			public const int cBtnAmount = 2131230785;
			
			// aapt resource value: 0x7f080002
			public const int cBtnCancel = 2131230722;
			
			// aapt resource value: 0x7f080011
			public const int cBtnClean = 2131230737;
			
			// aapt resource value: 0x7f080079
			public const int cBtnClose = 2131230841;
			
			// aapt resource value: 0x7f080040
			public const int cBtnCode = 2131230784;
			
			// aapt resource value: 0x7f08003c
			public const int cBtnDate = 2131230780;
			
			// aapt resource value: 0x7f080044
			public const int cBtnDesc = 2131230788;
			
			// aapt resource value: 0x7f080055
			public const int cBtnDiscount = 2131230805;
			
			// aapt resource value: 0x7f08003a
			public const int cBtnDo = 2131230778;
			
			// aapt resource value: 0x7f080064
			public const int cBtnDoAdd = 2131230820;
			
			// aapt resource value: 0x7f080063
			public const int cBtnDoAddPromo = 2131230819;
			
			// aapt resource value: 0x7f080062
			public const int cBtnDoAddPromoGlob = 2131230818;
			
			// aapt resource value: 0x7f080060
			public const int cBtnDoDelete = 2131230816;
			
			// aapt resource value: 0x7f080061
			public const int cBtnDoUseBarcode = 2131230817;
			
			// aapt resource value: 0x7f080016
			public const int cBtnMenu = 2131230742;
			
			// aapt resource value: 0x7f08003e
			public const int cBtnName = 2131230782;
			
			// aapt resource value: 0x7f080009
			public const int cBtnOk = 2131230729;
			
			// aapt resource value: 0x7f080059
			public const int cBtnPriceList = 2131230809;
			
			// aapt resource value: 0x7f080019
			public const int cBtnScan = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int cBtnScanExt = 2131230746;
			
			// aapt resource value: 0x7f080012
			public const int cBtnSearch = 2131230738;
			
			// aapt resource value: 0x7f080069
			public const int cBtnSourceWh = 2131230825;
			
			// aapt resource value: 0x7f080076
			public const int cBtnTest1 = 2131230838;
			
			// aapt resource value: 0x7f080077
			public const int cBtnTest2 = 2131230839;
			
			// aapt resource value: 0x7f080078
			public const int cBtnTest3 = 2131230840;
			
			// aapt resource value: 0x7f08006d
			public const int cBtnTextExt1 = 2131230829;
			
			// aapt resource value: 0x7f080071
			public const int cBtnTextExt2 = 2131230833;
			
			// aapt resource value: 0x7f080075
			public const int cBtnTextExt3 = 2131230837;
			
			// aapt resource value: 0x7f08002c
			public const int cBtnUnit = 2131230764;
			
			// aapt resource value: 0x7f08003f
			public const int cCode = 2131230783;
			
			// aapt resource value: 0x7f080021
			public const int cContext = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int cContextScroll = 2131230754;
			
			// aapt resource value: 0x7f080001
			public const int cData = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int cDate = 2131230726;
			
			// aapt resource value: 0x7f080043
			public const int cDesc = 2131230787;
			
			// aapt resource value: 0x7f08002e
			public const int cDiscount = 2131230766;
			
			// aapt resource value: 0x7f080010
			public const int cFilterText = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int cGrid = 2131230740;
			
			// aapt resource value: 0x7f08005e
			public const int cGrid2 = 2131230814;
			
			// aapt resource value: 0x7f08000d
			public const int cGridFL1 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int cGridFL2 = 2131230734;
			
			// aapt resource value: 0x7f08006b
			public const int cLabelExt1 = 2131230827;
			
			// aapt resource value: 0x7f08006f
			public const int cLabelExt2 = 2131230831;
			
			// aapt resource value: 0x7f080073
			public const int cLabelExt3 = 2131230835;
			
			// aapt resource value: 0x7f080067
			public const int cLabelSourceWh = 2131230823;
			
			// aapt resource value: 0x7f08002a
			public const int cLabelUnit = 2131230762;
			
			// aapt resource value: 0x7f08003d
			public const int cName = 2131230781;
			
			// aapt resource value: 0x7f08001c
			public const int cNumEdit = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int cNumInput = 2131230749;
			
			// aapt resource value: 0x7f080045
			public const int cPages = 2131230789;
			
			// aapt resource value: 0x7f080003
			public const int cPanel = 2131230723;
			
			// aapt resource value: 0x7f080023
			public const int cPanelAmount = 2131230755;
			
			// aapt resource value: 0x7f080032
			public const int cPanelData = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int cPanelDataWrap = 2131230771;
			
			// aapt resource value: 0x7f08002d
			public const int cPanelDiscount = 2131230765;
			
			// aapt resource value: 0x7f080048
			public const int cPanelDocInfo = 2131230792;
			
			// aapt resource value: 0x7f08006a
			public const int cPanelExt1 = 2131230826;
			
			// aapt resource value: 0x7f08006e
			public const int cPanelExt2 = 2131230830;
			
			// aapt resource value: 0x7f080072
			public const int cPanelExt3 = 2131230834;
			
			// aapt resource value: 0x7f08000a
			public const int cPanelFilter = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int cPanelFilter2 = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int cPanelFilter3 = 2131230735;
			
			// aapt resource value: 0x7f08004a
			public const int cPanelFin = 2131230794;
			
			// aapt resource value: 0x7f080013
			public const int cPanelGrid = 2131230739;
			
			// aapt resource value: 0x7f08001e
			public const int cPanelMain = 2131230750;
			
			// aapt resource value: 0x7f080020
			public const int cPanelMenu = 2131230752;
			
			// aapt resource value: 0x7f08005d
			public const int cPanelPageData = 2131230813;
			
			// aapt resource value: 0x7f080065
			public const int cPanelPageExt = 2131230821;
			
			// aapt resource value: 0x7f080046
			public const int cPanelPageMain = 2131230790;
			
			// aapt resource value: 0x7f080026
			public const int cPanelPrice = 2131230758;
			
			// aapt resource value: 0x7f080066
			public const int cPanelSourceWh = 2131230822;
			
			// aapt resource value: 0x7f08002f
			public const int cPanelTotal = 2131230767;
			
			// aapt resource value: 0x7f080029
			public const int cPanelUnit = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int cPrice = 2131230760;
			
			// aapt resource value: 0x7f080058
			public const int cPriceList = 2131230808;
			
			// aapt resource value: 0x7f080068
			public const int cSourceWh = 2131230824;
			
			// aapt resource value: 0x7f080018
			public const int cString = 2131230744;
			
			// aapt resource value: 0x7f080004
			public const int cText = 2131230724;
			
			// aapt resource value: 0x7f08006c
			public const int cTextExt1 = 2131230828;
			
			// aapt resource value: 0x7f080070
			public const int cTextExt2 = 2131230832;
			
			// aapt resource value: 0x7f080074
			public const int cTextExt3 = 2131230836;
			
			// aapt resource value: 0x7f080007
			public const int cTime = 2131230727;
			
			// aapt resource value: 0x7f080031
			public const int cTotal = 2131230769;
			
			// aapt resource value: 0x7f08001f
			public const int cTree = 2131230751;
			
			// aapt resource value: 0x7f08000b
			public const int cTreeF = 2131230731;
			
			// aapt resource value: 0x7f08003b
			public const int cTreeNodeText = 2131230779;
			
			// aapt resource value: 0x7f08002b
			public const int cUnit = 2131230763;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			// aapt resource value: 0x7f08004e
			public const int linearLayout10 = 2131230798;
			
			// aapt resource value: 0x7f080050
			public const int linearLayout11 = 2131230800;
			
			// aapt resource value: 0x7f080053
			public const int linearLayout13 = 2131230803;
			
			// aapt resource value: 0x7f080056
			public const int linearLayout14 = 2131230806;
			
			// aapt resource value: 0x7f08005a
			public const int linearLayout15 = 2131230810;
			
			// aapt resource value: 0x7f08005c
			public const int linearLayout16 = 2131230812;
			
			// aapt resource value: 0x7f080005
			public const int linearLayout2 = 2131230725;
			
			// aapt resource value: 0x7f08005f
			public const int linearLayout20 = 2131230815;
			
			// aapt resource value: 0x7f08004b
			public const int linearLayout21 = 2131230795;
			
			// aapt resource value: 0x7f080047
			public const int linearLayout22 = 2131230791;
			
			// aapt resource value: 0x7f080052
			public const int linearLayout23 = 2131230802;
			
			// aapt resource value: 0x7f080008
			public const int linearLayout3 = 2131230728;
			
			// aapt resource value: 0x7f080038
			public const int linearLayout4 = 2131230776;
			
			// aapt resource value: 0x7f080034
			public const int linearLayout5 = 2131230772;
			
			// aapt resource value: 0x7f080042
			public const int linearLayout6 = 2131230786;
			
			// aapt resource value: 0x7f080049
			public const int linearLayout7 = 2131230793;
			
			// aapt resource value: 0x7f08004c
			public const int linearLayout9 = 2131230796;
			
			// aapt resource value: 0x7f080015
			public const int relativeLayout1 = 2131230741;
			
			// aapt resource value: 0x7f080039
			public const int text = 2131230777;
			
			// aapt resource value: 0x7f080030
			public const int textView1 = 2131230768;
			
			// aapt resource value: 0x7f08004f
			public const int textView10 = 2131230799;
			
			// aapt resource value: 0x7f080051
			public const int textView11 = 2131230801;
			
			// aapt resource value: 0x7f080054
			public const int textView12 = 2131230804;
			
			// aapt resource value: 0x7f080057
			public const int textView13 = 2131230807;
			
			// aapt resource value: 0x7f080027
			public const int textView2 = 2131230759;
			
			// aapt resource value: 0x7f080025
			public const int textView3 = 2131230757;
			
			// aapt resource value: 0x7f080035
			public const int textView4 = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int textView5 = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int textView6 = 2131230775;
			
			// aapt resource value: 0x7f08005b
			public const int textView7 = 2131230811;
			
			// aapt resource value: 0x7f08004d
			public const int textView9 = 2131230797;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int form = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FormUserHandlerLog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MobDataGridCell = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MobDataGridHeader = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MobDataGridHeaderRow = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MobDataGridRow = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MobDataReferenceDateSelectForm = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MobDataReferenceGridFormBase = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MobDataReferenceStringSelectForm = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MobDataReferenceValueSelectBarcodeForm = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MobDataReferenceValueSelectNumForm = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MobFormMain = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MobFormShowData = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MobInputItemVarsForm = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int MobListViewItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MobMenuItem = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int MobNumInput = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int MobTreeViewChild = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int MobTreeViewGroup = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int MobUserEditorFormCashIO = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int MobUserEditorFormMaterialDoc = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int MobUserEditorFormMaterialDocShort = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int test = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int ControlGrid = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ControlTree = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070008
			public const int Button = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int ButtonClick = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int ButtonClickDummy = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int ButtonClickGroupItem = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int ButtonClickToolItem = 2131165193;
			
			// aapt resource value: 0x7f070013
			public const int Grid = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int GridCell = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int GridCellText = 2131165207;
			
			// aapt resource value: 0x7f070014
			public const int GridHeader = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int GridHeaderText = 2131165205;
			
			// aapt resource value: 0x7f070011
			public const int Label = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int LabelDummy = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int LineH = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int LinePadH = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int LineV = 2131165186;
			
			// aapt resource value: 0x7f07000e
			public const int Number = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int NumberNoClick = 2131165199;
			
			// aapt resource value: 0x7f070001
			public const int Panel = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Tabs = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int Text = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int TextArea = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int TextAreaInfo = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int TextDesc = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int TextDummy = 2131165195;
			
			// aapt resource value: 0x7f070018
			public const int Tree = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int TreeGroup = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int TreeGroupText = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int TreeItem = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int TreeItemText = 2131165212;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
