SELECT DOC.DATE_,
	SUBSTR(CL.DEFINITION_, 1, 25) NAME,
	DOC.NETTOTAL TOTAL,
	SUBSTR(DOC.GENEXP1, 1, 1) GENEXP1
FROM LG_$FIRM$_$PERIOD$_INVOICE DOC
INNER JOIN LG_$FIRM$_CLCARD CL ON DOC.CLIENTREF = CL.LOGICALREF
WHERE DOC.TRCODE = 8
	AND DOC.CANCELLED = 0
ORDER BY DOC.DATE_ ASC
GO

SELECT DOC.DATE_,
	SUBSTR(CL.DEFINITION_, 1, 25) NAME,
	DOC.NETTOTAL TOTAL,
	SUBSTR(DOC.GENEXP1, 1, 1) GENEXP1
FROM LG_$FIRM$_$PERIOD$_INVOICE DOC
INNER JOIN LG_$FIRM$_CLCARD CL ON DOC.CLIENTREF = CL.LOGICALREF
WHERE DOC.TRCODE = 3
	AND DOC.CANCELLED = 0
ORDER BY DOC.DATE_ ASC
GO

SELECT DOC.DATE_,
	SUBSTR(CL.DEFINITION_, 1, 25) NAME,
	DOC.AMOUNT TOTAL,
	SUBSTR(DOC.LINEEXP, 1, 1) GENEXP1
FROM LG_$FIRM$_$PERIOD$_KSLINES DOC
INNER JOIN LG_$FIRM$_CLCARD CL ON DOC.CLIENTREF = CL.LOGICALREF
WHERE DOC.TRCODE = 11
	AND DOC.CANCELLED = 0
ORDER BY DOC.DATE_ ASC
GO
SELECT SALES,SALESRET,(SALES-SALESRET) SALESNET, PROFIT FROM (
SELECT IFNULL(SUM((
			CASE 
				WHEN DOC.TRCODE = 8
					THEN 1
				ELSE 0
				END
			) * LINE.TOTAL * (100 - LINE.DISCPER) / 100 * (100 - DOC.DISCPER) / 100),0.0) SALES,
	IFNULL(SUM((
			CASE 
				WHEN DOC.TRCODE = 3
					THEN 1
				ELSE 0
				END
			) * LINE.TOTAL * (100 - LINE.DISCPER) / 100 * (100 - DOC.DISCPER) / 100),0.0) SALESRET,
	IFNULL(SUM((
			CASE 
				WHEN DOC.TRCODE = 8
					THEN + 1
				WHEN DOC.TRCODE = 2
					THEN - 1
				ELSE 0
				END
			) * LINE.TOTAL * (100 - LINE.DISCPER) / 100 * (100 - DOC.DISCPER) / 100 - LINE.AMOUNT * ITEMS.COSTPRC),0.0) PROFIT
FROM LG_000_00_INVOICE DOC
INNER JOIN LG_000_00_STLINE LINE ON DOC.LOGICALREF = LINE.STDOCREF
INNER JOIN LG_000_ITEMS ITEMS ON LINE.STOCKREF = ITEMS.LOGICALREF
WHERE DOC.CANCELLED = 0
	AND LINE.LINETYPE = 0
 ) T
GO


