SELECT
	ORFICHE.LOGICALREF,
	ORFICHE.DATE_,
	ORFICHE.NETTOTAL,
	ORFICHE.CANCELLED,
	ORFICHE.READONLY,
	(SELECT T.DEFINITION_ FROM LG_$FIRM$_CLCARD T WHERE T.LOGICALREF = ORFICHE.CLIENTREF) CLCARD_____DEFINITION_
FROM
LG_$FIRM$_$PERIOD$_ORFICHE ORFICHE
$WHERE$
$ORDER$
$LIMIT$