SELECT
CL.DEFINITION_ NAME, 
DOC.AMOUNT TOTAL
FROM 
LG_$FIRM$_$PERIOD$_KSLINES DOC 
INNER JOIN
LG_000_CLCARD CL 
ON DOC.CLIENTREF = CL.LOGICALREF
WHERE 
DOC.TRCODE = 11 AND
DOC.CANCELLED = 0 
ORDER BY DOC.DATE_ DESC
GO
