using System;
using System.Collections.Generic;
using System.Text;

namespace AvaExt.Manual.Table
{
    public class TableORFLINE
    {
        public const String TABLE_RECORD_ID = "LG_$FIRM$_$PERIOD$_ORFLINESEQ";
        public const String TABLE = "ORFLINE";
        public const String TABLE_LONG = "LG_$FIRM$_$PERIOD$_ORFLINE";
        public const String LOGICALREF = "LOGICALREF"; // int 4
        public const String STOCKREF = "STOCKREF"; // int 4
     // public const String ORDFICHEREF = "ORDFICHEREF"; // int 4
        public const String CLIENTREF = "CLIENTREF"; // int 4
        public const String LINETYPE = "LINETYPE"; // smallint 2
        public const String PREVLINEREF = "PREVLINEREF"; // int 4
        public const String PREVLINENO = "PREVLINENO"; // smallint 2
        public const String DETLINE = "DETLINE"; // smallint 2
        public const String LINENO_ = "LINENO_"; // smallint 2
        public const String TRCODE = "TRCODE"; // smallint 2
        public const String DATE_ = "DATE_"; // datetime 8
        public const String TIME_ = "TIME_"; // int 4
        public const String GLOBTRANS = "GLOBTRANS"; // smallint 2
        public const String CALCTYPE = "CALCTYPE"; // smallint 2
        public const String CENTERREF = "CENTERREF"; // int 4
        public const String ACCOUNTREF = "ACCOUNTREF"; // int 4
        public const String VATACCREF = "VATACCREF"; // int 4
        public const String VATCENTERREF = "VATCENTERREF"; // int 4
        public const String PRACCREF = "PRACCREF"; // int 4
        public const String PRCENTERREF = "PRCENTERREF"; // int 4
        public const String PRVATACCREF = "PRVATACCREF"; // int 4
        public const String PRVATCENREF = "PRVATCENREF"; // int 4
        public const String PROMREF = "PROMREF"; // int 4
        public const String SPECODE = "SPECODE"; // varchar 17
        public const String DELVRYCODE = "DELVRYCODE"; // varchar 5
        public const String AMOUNT = "AMOUNT"; // float 8
        public const String PRICE = "PRICE"; // float 8
        public const String TOTAL = "TOTAL"; // float 8
        public const String SHIPPEDAMOUNT = "SHIPPEDAMOUNT"; // float 8
        public const String DISCPER = "DISCPER"; // float 8
        public const String DISTCOST = "DISTCOST"; // float 8
        public const String DISTDISC = "DISTDISC"; // float 8
        public const String DISTEXP = "DISTEXP"; // float 8
        public const String DISTPROM = "DISTPROM"; // float 8
        public const String VAT = "VAT"; // float 8
        public const String VATAMNT = "VATAMNT"; // float 8
        public const String VATMATRAH = "VATMATRAH"; // float 8
        public const String LINEEXP = "LINEEXP"; // varchar 31
        public const String UOMREF = "UOMREF"; // int 4
        public const String USREF = "USREF"; // int 4
        public const String UINFO1 = "UINFO1"; // float 8
        public const String UINFO2 = "UINFO2"; // float 8
        public const String UINFO3 = "UINFO3"; // float 8
        public const String UINFO4 = "UINFO4"; // float 8
        public const String UINFO5 = "UINFO5"; // float 8
        public const String UINFO6 = "UINFO6"; // float 8
        public const String UINFO7 = "UINFO7"; // float 8
        public const String UINFO8 = "UINFO8"; // float 8
        public const String VATINC = "VATINC"; // smallint 2
        public const String CLOSED = "CLOSED"; // smallint 2
        public const String DORESERVE = "DORESERVE"; // smallint 2
        public const String INUSE = "INUSE"; // smallint 2
        public const String DUEDATE = "DUEDATE"; // datetime 8
        public const String PRCURR = "PRCURR"; // smallint 2
        public const String PRPRICE = "PRPRICE"; // float 8
        public const String REPORTRATE = "REPORTRATE"; // float 8
        public const String BILLEDITEM = "BILLEDITEM"; // int 4
        public const String PAYDEFREF = "PAYDEFREF"; // int 4
        public const String EXTENREF = "EXTENREF"; // int 4
        public const String CPSTFLAG = "CPSTFLAG"; // smallint 2
        public const String SOURCEINDEX = "SOURCEINDEX"; // smallint 2
        public const String SOURCECOSTGRP = "SOURCECOSTGRP"; // smallint 2
        public const String BRANCH = "BRANCH"; // smallint 2
        public const String DEPARTMENT = "DEPARTMENT"; // smallint 2
        public const String LINENET = "LINENET"; // float 8
        public const String SALESMANREF = "SALESMANREF"; // int 4
        public const String STATUS = "STATUS"; // smallint 2
        public const String DREF = "DREF"; // int 4
        public const String TRGFLAG = "TRGFLAG"; // smallint 2
        public const String SITEID = "SITEID"; // smallint 2
        public const String RECSTATUS = "RECSTATUS"; // smallint 2
        public const String ORGLOGICREF = "ORGLOGICREF"; // int 4
        public const String FACTORYNR = "FACTORYNR"; // smallint 2
        public const String WFSTATUS = "WFSTATUS"; // int 4
        public const String NETDISCFLAG = "NETDISCFLAG"; // smallint 2
        public const String NETDISCPERC = "NETDISCPERC"; // float 8
        public const String NETDISCAMNT = "NETDISCAMNT"; // float 8
        public const String CONDITIONREF = "CONDITIONREF"; // int 4
        public const String DISTRESERVED = "DISTRESERVED"; // float 8
        public const String ONVEHICLE = "ONVEHICLE"; // float 8
        public const String CAMPAIGNREFS1 = "CAMPAIGNREFS1"; // int 4
        public const String CAMPAIGNREFS2 = "CAMPAIGNREFS2"; // int 4
        public const String CAMPAIGNREFS3 = "CAMPAIGNREFS3"; // int 4
        public const String CAMPAIGNREFS4 = "CAMPAIGNREFS4"; // int 4
        public const String CAMPAIGNREFS5 = "CAMPAIGNREFS5"; // int 4
        public const String POINTCAMPREF = "POINTCAMPREF"; // int 4
        public const String CAMPPOINT = "CAMPPOINT"; // float 8
        public const String PROMCLASITEMREF = "PROMCLASITEMREF"; // int 4
        public const String REASONFORNOTSHP = "REASONFORNOTSHP"; // smallint 2
        public const String CMPGLINEREF = "CMPGLINEREF"; // int 4
        public const String PRRATE = "PRRATE"; // float 8
        public const String GROSSUINFO1 = "GROSSUINFO1"; // float 8
        public const String GROSSUINFO2 = "GROSSUINFO2"; // float 8
        public const String CANCELLED = "CANCELLED"; // smallint 2
        public const String DEMPEGGEDAMNT = "DEMPEGGEDAMNT"; // float 8
        public const String TEXTINC = "TEXTINC"; // smallint 2
        public const String OFFERREF = "OFFERREF"; // int 4
        public const String ORDERPARAM = "ORDERPARAM"; // smallint 2
        public const String ITEMASGREF = "ITEMASGREF"; // int 4
        public const String EXIMAMOUNT = "EXIMAMOUNT"; // float 8
        public const String OFFTRANSREF = "OFFTRANSREF"; // int 4
        public const String ORDEREDAMOUNT = "ORDEREDAMOUNT"; // float 8
        public const String ORGLOGOID = "ORGLOGOID"; // varchar 25
        public const String TRCURR = "TRCURR"; // smallint 2
        public const String TRRATE = "TRRATE"; // float 8
        public const String WITHPAYTRANS = "WITHPAYTRANS"; // smallint 2
        public const String PROJECTREF = "PROJECTREF"; // int 4
        public const String POINTCAMPREFS1 = "POINTCAMPREFS1"; // int 4
        public const String POINTCAMPREFS2 = "POINTCAMPREFS2"; // int 4
        public const String POINTCAMPREFS3 = "POINTCAMPREFS3"; // int 4
        public const String POINTCAMPREFS4 = "POINTCAMPREFS4"; // int 4
        public const String CAMPPOINTS1 = "CAMPPOINTS1"; // float 8
        public const String CAMPPOINTS2 = "CAMPPOINTS2"; // float 8
        public const String CAMPPOINTS3 = "CAMPPOINTS3"; // float 8
        public const String CAMPPOINTS4 = "CAMPPOINTS4"; // float 8
        public const String CMPGLINEREFS1 = "CMPGLINEREFS1"; // int 4
        public const String CMPGLINEREFS2 = "CMPGLINEREFS2"; // int 4
        public const String CMPGLINEREFS3 = "CMPGLINEREFS3"; // int 4
        public const String CMPGLINEREFS4 = "CMPGLINEREFS4"; // int 4
        public const String PRCLISTREF = "PRCLISTREF"; // int 4

        public const String AMOUNT3 = "AMOUNT3"; // float 8
        public const String AMOUNT2 = "AMOUNT2"; // float 8
        public const String AMOUNT1 = "AMOUNT1"; // float 8
    }
}
